# Generated by Django 4.1.4 on 2023-03-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
